### PR TITLE
I have udpated two line in feature2 

### PR DESCRIPTION
**Pull request by SprintQA**
modified my lines and i am sure i haven't mess up.

I have tested thoroughly.

### CODE REVIEW

**Comment by mfuyar** [comment]
it seems ok:)

**Comment by LanaRechkalova** [comment]
add some nested  loops

**Comment by Anvar2401** [comment]
failed ...

**Comment by SprintQA** [comment]
Please approve....I'll give you one chocolate from my side

**Comment by mfuyar** [comment]
As you wish

**Comment by mfuyar** [comment]
I did:)

**Comment by mfuyar** [comment]
Go, i will help you

**Pull request merged**
